#!/usr/bin/env bash
# -m|--multi || Whether or not to allow multi-selection.
#
# Open a fd for UI text
exec {ui}>&2
#
# Grab args
args="$(getopt --options mt: --longoptions multi,title: -- "$@")"
eval set -- "${args[*]}"
while true; do
	case "$1" in
		-m|--multi)
			multi=true
			shift
		;;
		-t|--title)
			title="$2"
			shift 2
		;;
		--)
			shift
			break
		;;
		*)
			break
		;;
	esac
done
entries=("$@")
#
# Display options
clear >&"${ui}"
[[ -n "${preprompt_msg}" ]] && echo "${preprompt_msg}" >&"${ui}"
echo "${title}" >&"${ui}"
for item in "${entries[@]}"; do
	x="$((x + 1))"
	item="${x}) ${item}"
	echo "    ${item}" >&"${ui}"
done
#
# Determinte selection mode & grab selection(s)
if [[ -n "${multi}" ]]; then
	cat >&"${ui}" <<-'EOF'
		Enter your selections—separated by spaces.
		(i.e. "1 4 6 9")
	EOF
else
	cat >&"${ui}" <<-'EOF'
		Enter a single selection
		(i.e. "5")
	EOF
fi
read -erp 'Type your selection(s) then press [ENTER] to submit: ' -a selections >&"${ui}"
#
# Do nothing with empty responses
# Validate user choices & return the choices
[[ -z "${selections[*]}" ]] && exit 0
[[ -z "${multi}" && "${#selections[@]}" -gt 1 ]] && exit 255
for selection in "${selections[@]}"; do
	[[
		"${selection}" =~ ^[0-9]+$ &&
		"${selection}" -gt 0 &&
		"${selection}" -le "$#"
	]] && echo "${entries["$(("${selection}" - 1 ))"]}"
done