#!/usr/bin/env bash
cl-legacy() {
	local ui='' item selections selection x=0 entries multi=0 optional=0
	exec {ui}>&2
	#
	# Grab args
	while ((${#} > 0)); do
	  	case "${1}" in
		--multi)
			multi=1
			shift
			;;
		--optional)
			optional=1
			shift
			;;
		--)
			shift
			break
			;;
		--*)
			log e "Unknown long-form option: ${1}"
			return 2
			;;
		-*)
			for ((i=1; i<${#1}; i++)); do
				case "${1:i:1}" in
				m)
					multi=1
					;;
				o)
					optional=1
					;;
				*)
					log e "Unknown short-form option: -${1:i:1}"
					return 2
					;;
				esac
			done
			shift
			;;
		*)
			break
			;;
		esac
	done
	entries=("$@")
	#
	# Display options
	{
		clear -x
		[[ -n "${PS3}" ]] && echo "${PS3}"
		printf "%s\n" "${PS2}"
		for item in "${entries[@]}"; do
			((x++))
			[[ -n "${item}" ]] && printf "\t%s) %s\n" "${x}" "${item}"
		done
		#
		# Determinte selection mode & grab selection(s)
		if ((multi)); then
			printf '%s' 'Multi-select (i.e. "1 4 6 9") '
		else
			printf '%s' 'Single-select (i.e. "5") '
		fi
		if ((optional)); then
			printf '%s\n' '* Selection Required'
		else
			echo
		fi
		existing_trap="$(trap -p SIGINT)"
		trap 'trap "${existing_trap}" SIGINT; return 130' SIGINT
		if ((!optional)); then
			printf 'Type, then press [ENTER] to submit: '
			while ((!${#selections[@]})); do
				read -era selections
			done
		else
			read -erp 'Type, then press [ENTER] to submit: ' -a selections
		fi
		trap '${existing_trap}' SIGINT
	} >&"${ui}"
	#
	# Do nothing with empty responses and validate user choices then return the choices.
	((!multi)) && [[ "${#selections[@]}" -gt 1 ]] && return 1
	if ((multi)); then
		for selection in "${selections[@]}"; do
			printf '%s\0' "${entries["$(("${selection}" - 1 ))"]}"
		done
	else
		printf '%s' "${entries["${selections[0]}"]}"
	fi
}
export -f cl-legacy
