#!/usr/bin/env bash
cl-legacy() {
	local ui item selections selection x=0
	#
	# Open a fd for UI text if there isn't already one open.
	[[ "${ui}" =~ ^[0-9]+$ ]] || exec {ui}>&2
	#
	# Grab args
	local args
	args="$(getopt --options mt: --longoptions multi,title: -- "$@")"
	eval set -- "${args[*]}"
	while true; do
		case "${1}" in
			-m|--multi)
				local multi=1
				shift
			;;
			-t|--title)
				local title="${2}"
				shift 2
			;;
			--)
				shift
				break
			;;
			*)
				break
			;;
		esac
	done
	local entries=("$@")
	#
	# Display options
	clear -x >&"${ui}"
	[[ -n "${PS3}" ]] && echo "${PS3}" >&"${ui}"
	printf "%s\n" "${title}" >&"${ui}"
	for item in "${entries[@]}"; do
		((x++))
		[[ -n "${item}" ]] && printf "\t%s) %s\n" "${x}" "${item}" >&"${ui}"
	done
	#
	# Determinte selection mode & grab selection(s)
	if ((multi)); then
		printf '%s\n' 'Multi-select (i.e. "1 4 6 9")' >&"${ui}"
	else
		printf '%s\n' 'Single-select (i.e. "5")' >&"${ui}"
	fi
	read -erp 'Type, then press [ENTER] to submit: ' -a selections >&"${ui}"
	#
	# Do nothing with empty responses and validate user choices then return the choices.
	[[ "${#selections[@]}" == 0 ]] && return 0
	((!multi)) && [[ "${#selections[@]}" -gt 1 ]] && return 1
	for selection in "${selections[@]}"; do
		[[
			"${selection}" =~ ^[0-9]+$ &&
			"${selection}" -gt 0 &&
			"${selection}" -le "${#entries[@]}"
		]] && printf '%s\0' "${entries["$(("${selection}" - 1 ))"]}"
	done
}
export -f cl-legacy
