#!/usr/bin/env bash
confirm() {
	local answer=''
	until [[ "${answer}" =~ ^[YyNn]$ ]]; do
		clear -x
		[[ -n "${PS3}" ]] && printf -- '%s\n' "${PS3}"
		printf "%s? [y/n]: \n" "${1}"
		read -e answer
		answer="${answer:0:1}"
	done
	[[ "${answer}" =~ ^[Yy]$ ]]
}
export -f confirm
