#!/usr/bin/env bash
find() {
	local arg args
	for arg in "${@}"; do
		if [[ "${arg}" == '-xephem' ]]; then
			args+=(
				'('
				-path /tmp
				-o -path /run
				-o -path /dev
				-o -path /proc
				-o -path /sys
				-o -path /var/run
				-o -path /var/lock
				-o -path /var/tmp
				')'
				-prune
				-o
			)
		else
			args+=("${arg}")
		fi
	done
	[[ "${args[-1]}" == '-o' ]] && args+=(-print)
	command find "${args[@]}"
}
export -f find
