#!/usr/bin/env bash
# ANSII escapes for coloring output
declare -A ansii
ansii[blue]='\033[48;5;18m'
ansii[yellow]='\033[48;5;58m'
ansii[red]='\033[48;5;88m'
ansii[reset]='\033[0m'
#
# Catch recursive failure
if [[ -n "${error_recurse}" ]]; then
	printf "%bE: Recursive failure of the \"log\" library function was detected and the command has been terminated.%b\n" "${ansii[red]}" "${ansii[reset]}"
	exit 255
fi
#
# Catch arguments (if no input in args, grab input from stdin.)
type="$1"; shift 1
[[ -t 0 && -n "$1" ]] && input="$*" || input="$(</dev/stdin)"
#
# If no input, error out.
if [[ -z "${input}" ]]; then
	log e 'Missing message for "log" library command.'
	exit 254
fi
#
# Parse input
case "${type}" in
	i) printf -- '%bℹ: %s' "${ansii[blue]}" "${input}";;
	w) printf -- '%bW: %s' "${ansii[yellow]}" "${input}" >&2;;
	e) printf -- '%bE: %s' "${ansii[red]}" "${input}" >&2;;
	*)
		log e "Invalid log type \"${type}\". Valid options are \"i\" (info), \"w\" (warning), or \"e\" (error)."
		exit 253
	;;
esac
#
# Stop color from leaking & prints newline.
printf '%b\n' "${ansii[reset]}"