#!/usr/bin/env bash
pause() {
	local seconds="${1:-10}"
	read -t "${seconds}" -n1 -rp "(Auto-resuming in ${seconds} seconds...)"$'\n⏸ ⏸ ⏸ > > PRESS ANY KEY TO RESUME < < ⏸ ⏸ ⏸\n'
	log i "Resumed script."
}
export -f pause
