#!/usr/bin/env bash
perm_fix() {
	local errors path before after
	#
	# Parse arguments
	while getopts 'm:o:g:' arg; do
		case "${arg}" in
			m) local mode="${OPTARG}";;
			o) local owner="${OPTARG}";;
			g) local group="${OPTARG}";;
			f) local force=true;;
			*)
				log e "Invalid opt."
				return 1
			;;
		esac
	done
	#
	# Validate user:group/octal permissions
	[[ -n "${owner}" && ! "${owner}" =~ ^[0-9]+$ ]] ||
		getent passwd -- "${owner}" &>/dev/null ||
		errors+=("${owner} is an invalid user.")
	[[ -n "${group}" && ! "${group}" =~ ^[0-9]+$ ]] ||
		getent group -- "${group}" &>/dev/null ||
		errors+=("${group} is an invalid group.")
	[[ -n "${mode}" && ! "${mode}" =~ ^[01234567]{3,4} ]] &&
		errors+=("${mode} is an invalid octal mode.")
	if [[ "${#errors[@]}" -ge 1 ]]; then
		log e "${errors[@]}"
		return 1
	fi
	#
	# Shift by the amount of getopts to get our paths
	shift "$((OPTIND - 1))"
	#
	# Iterate over every path
	for path in "$@"; do
		# Validate path
		[[ -L "${path}" ]] && log w "\"${path}\" is a symlink to \"$(realpath "${path}")\"."
		[[ -L "${path}" && "${force}" == true ]] && { log e 'Refused to process symlinks without the "-f" opt...'; return 2; }
		#
		# Create non-existent files
		if [[ ! -e "${path}" ]]; then
			mkdir -p "$(dirname -- "${path}")"
			: >>"${path}"
		fi
		#
		# Save stats for file pre-change
		before="$(stat -c '%a %u/%U:%g/%G' -- "${path}")"
		#
		# Attempt the change
		chown -h -- "${owner}:${group}" "${path}" || return 3
		[[ -n "${mode}" ]] && chmod -- "${mode}" "${path}" || return 4
		#
		# Check stats for file post-change
		after="$(stat -c '%a %u/%U:%g/%G' -- "${path}")"
		#
		# Log diffs bewteen pre and post stats
		[[ "${before}" != "${after}" ]] && log w "${path} with \"${before}\" deviated from, and was restored to \"${after}\"."
	done
}
export -f perm_fix