#!/usr/bin/env bash
perm_fix() {
	local errors path before after mode owner group force=0
	#
	# Parse arguments
	while getopts 'm:o:g:f' arg; do
		case "${arg}" in
			m)
				mode="${OPTARG}"
				[[ "${mode}" =~ ^[01234567]{3,4}$ ]] ||
					errors+=("perm_fix: \"${mode}\" is an invalid octal mode.")
				;;
			o)
				owner="${OPTARG}"
				[[ "${owner}" =~ ^[0-9]+$ ]] ||
					getent passwd -- "${owner}" &> /dev/null ||
					errors+=("perm_fix: \"${owner}\" is an invalid user.")
				;;
			g)
				group="${OPTARG}"
				[[ "${group}" =~ ^[0-9]+$ ]] ||
					getent group -- "${group}" &> /dev/null ||
					errors+=("perm_fix: \"${group}\" is an invalid group.")
				;;
			f) force=1 ;;
			*)
				log e "perm_fix: Invalid option \"${arg}\"."
				return 1
			;;
		esac
	done
	if ! ((${#mode} + ${#owner} + ${#group} || ${#*})); then
		errors+=('perm_fix: Missing operand')
	fi
	if [[ "${#errors[@]}" -ge 1 ]]; then
		log e "${errors[@]}"
		return 1
	fi
	#
	# Shift by the amount of getopts to get our paths
	shift "$((OPTIND - 1))"
	#
	# Iterate over every path
	for path in "${@}"; do
		# Validate path
		[[ -L "${path}" ]] && log w "\"${path}\" is a symlink to \"$(realpath -- "${path}")\"."
		if [[ -L "${path}" ]] && ((force)); then
			log e 'perm_fix: Refused to process symlink without option -f.'
			return 2
		fi
		#
		# Create non-existent files
		if [[ ! -e "${path}" ]]; then
			log e "File ${path@Q} doesn't exist."
			return 5
		fi
		#
		# Attempt the change
		if [[ -n "${owner}" && -n "${group}" ]]; then
			chown -hv -- "${owner}:${group}" "${path}" || return 3
		elif [[ -n "${owner}" && -z "${group}" ]]; then
			chown -hv -- "${owner}" "${path}" || return 3
		elif [[ -z "${owner}" && -n "${group}" ]]; then
			chgrp -hv -- "${group}" "${path}" || return 3
		fi
		if [[ -n "${mode}" ]]; then
			chmod -v -- "${mode}" "${path}" || return 4
		fi
	done
}
export -f perm_fix
