#!/usr/bin/env bash
# Parse arguments
while getopts 'm:o:g:' arg; do
	case "${arg}" in
		m) mode="${OPTARG}";;
		o) owner="${OPTARG}";;
		g) group="${OPTARG}";;
		*)
			error "Invalid argument."
			exit 255
		;;
	esac
done
#
# Validate user:group
# Validate permissions
if
	[[ -n "${owner}" && ! "${owner}" =~ ^[0-9]+$ ]] ||
	! getent passwd -- "${owner}" &>/dev/null
then
	errors+=("${owner} is an invalid user.")
elif
	[[ -n "${group}" && ! "${group}" =~ ^[0-9]+$ ]] ||
	! getent group -- "${group}" &>/dev/null
then
	errors+=("${group} is an invalid group.")
elif [[ -n "${mode}" && ! "${mode}" =~ ^[01234567]{3,4} ]]; then
	errors+=("${mode} is an invalid mode.")
fi
if [[ -n "${errors[*]}" ]]; then
	for error in "${errors[@]}"; do log e "${error}"; done
	exit 254
fi
#
# Shift by the amount of getopts to get our paths
shift "$(( OPTIND - 1 ))"
#
# Iterate over every path
for path in "$@"; do
	# Create non-existent files
	touch -- "${path}"
	#
	# Save stats for file pre-change
	before="$(stat -c '%a %u/%U:%g/%G' -- "${path}")"
	#
	# Attempt the change
	chown -hP -- "${owner}:${group}" "${path}"
	[[ -n "${mode}" ]] && chmod -hP -- "${mode}" "${path}"
	#
	# Check stats for file post-change
	after="$(stat -c '%a %u/%U:%g/%G' -- "${path}")"
	#
	# Log diffs bewteen pre and post stats
	[[ "${before}" != "${after}" ]] &&
		log w "${path} with \"${before}\" deviated from, and was restored to \"${after}\"."
done