#!/usr/bin/env bash
reconfig() {
	# Parse arguments
	local delimiter=' ' exception='abort' create_nonexistent=0
	while getopts 'd:x:p' arg; do
		case "${arg}" in
		d) delimiter="${OPTARG}" ;;
		x) exception="${OPTARG}" ;;
		p) create_nonexistent=1 ;;
		*)
			log e "Invalid shortform option."
			return 1
			;;
		esac
	done
	shift "$((OPTIND - 1))"
	#
	# Create non-existent path if specified.
	if [[ -f "${3}" ]] || ((create_nonexistent)); then
		mkdir -p "$(dirname "${3}")" && true >> "${3}"
	elif [[ -d "${3}" ]]; then
		log e "\"${3}\" is a directory!"
	else
		log e "The provided path \"${3}\" doesn't exist!"
		return 3
	fi
	#
	# Detect duplicates
	local duplicate=0
	grep -qE "^[^#].*${1}${delimiter}.*$" "${3}" && duplicate=1
	#
	# Handle duplicate entries accordingly
	((duplicate)) && case "${exception}" in
	replace)
		sed -i "s/^[^#]*${1}.*$/${1}${delimiter}${2}/" "${3}"
		return
		;;
	append)
		echo "${1}${delimiter}${2}" >> "${3}"
		return
		;;
	abort)
		log e "The key \"${1}\" was already defined in \"${3}\". The operation was aborted and \"${1}\" was not set to \"${2}\"."
		return 2
		;;
	*)
		log e "The value \"${exception}\" for the -x opt is invalid. The valid values are:"$'\n\t"replace", "append", or "abort".'
		return 1
		;;
	esac
	echo "${1}${delimiter}${2}" >> "${3}"
}
export -f reconfig
