#!/usr/bin/env bash
# shellcheck disable=SC2154
# Parse arguments
while getopts 'd:' arg; do
	case "${arg}" in
		d) delimiter="${OPTARG}";;
		*)
			error "Invalid argument."
			exit 255
		;;
	esac
done
delimiter="${delimiter:-' '}"
shift "$(( OPTIND - 1 ))"
#
# The divider used to delimitate the key and value; and the target file.
# Defined via an environment variable to avoid extreme repetition.
# Remove any existing keys & then add the new entry
touch "$3"
grep -qE "^[^#].*$1${delimiter}.*$" <"$3" &&
	sed -i "s/^[^#]*$1.*$/$1${delimiter}$2/" <"$3"
echo "$1${delimiter}$2" >>"$3"