#!/usr/bin/env bash
reconfig() {
	# Parse arguments
	local delimiter=' ' exception='abort' create_nonexistent=0 duplicate=0
	while getopts 'd:x:p' arg; do
		case "${arg}" in
		d)
			delimiter="${OPTARG}"
			shift 2
			;;
		x)
			exception="${OPTARG}"
			shift 2
			;;
		p)
			create_nonexistent=1
			shift
			;;
		*)
			log e "perm_fix: invalid shortform option: ${arg@Q}"
			return 1
			;;
		esac
	done
	#
	# Create non-existent path if specified.
	[[ -f "${3}" ]] || if ((create_nonexistent)); then
		mkdir -p "$(dirname "${3}")" && true >> "${3}"
	elif [[ -d "${3}" ]]; then
		log e "reconfig: cannot write to a directory: ${3@Q}"
	else
		log e "reconfig: ${3@Q} doesn't exist."
		return 3
	fi
	#
	# Handle duplicate entries accordingly
	grep -qE "^[^#].*${1}${delimiter}.*$" "${3}" && duplicate=1
	((duplicate)) && case "${exception}" in
	replace)
		sed -i "s/^[^#]*${1}.*$/${1}${delimiter}${2}/" "${3}"
		return
		;;
	append)
		echo "${1}${delimiter}${2}" >> "${3}"
		return
		;;
	abort)
		log e "perm_fix: operation aborted: ${1@Q} was already defined in ${3@Q}."
		return 2
		;;
	*)
		log e "${exception} is not a valid value for -x. Valid values are:"$'\n\t"replace", "append", or "abort".'
		return 1
		;;
	esac
	echo "${1}${delimiter}${2}" >> "${3}"
}
export -f reconfig
