#!/usr/bin/env bash
# Prompt for action
fixes=(
	'Change ownership'
	'Change permissions'
	'Rename'
	'' '' ''
	'Delete'
)
preprompt_msg+="\"$1\" is owned by $(stat -c '%U:%G/%u:%g' "$1") with permissions $(stat -c '%a' "$1")" \
	mapfile -t choices < <(checklist 'What do you want to do?' checklist "${fixes[@]}")
#
# Act on selections
for choice in "${choices[@]}"; do
	# Prompt for new ownership
	# Validate given user and group
	# Change the ownership
	if [[ "${choice}" == 'Change ownership' ]]; then
		until [[ "${user}" =~ ^[0-9]+$ ]] || getent passwd -- "${user}" &>/dev/null && [[ -n "${user}" ]]; do
			[[ -n "${x}" ]] && log w 'Invalid username/UID provided.' || x=true
			read -rp 'Enter the new user owner: ' user
		done
		until [[ "${user}" =~ ^[0-9]+$ ]] || getent group -- "${group}" &>/dev/null && [[ -n "${group}" ]]; do
			[[ -n "${y}" ]] && log w 'Invalid group/GID provided.' || y=true
			read -rp 'Enter the new group owner: ' group
		done
		chown -hc -- "${user}:${group}" "$1"
	#
	# Prompt for new permissions
	elif [[ "${choice}" == 'Change permissions' ]]; then
		until [[ "${perm}" =~ ^[1234567]{3,4}$ ]]
		do read -rp 'Enter the octal permission: ' perm
		done
		chmod -c -- "${perm}" "$1"
	# Prompt for new node name
	elif [[ "${choice}" == Rename ]]; then
		read -rp 'Enter the new name for the node' basename
		mv -- "$1" "$(dirname -- "$1")""${basename}"
	#
	# Delete the path
	elif [[ "${choice}" == Delete ]]; then
		rm -rfv -- "$1"
	fi
done