#!/usr/bin/env bash
for arg in "$@"; do
	if [[ "${arg}" == '-xdev' ]]; then
		args+=(
			-not '('
			-path /tmp
			-o -path /run
			-o -path /dev
			-o -path /proc
			-o -path /sys
			-o -path /var/run
			-o -path /var/lock
			-o -path /var/tmp
			')'
		)
	else args+=("${arg}")
	fi
done
find "${args[@]}"